language: python
matrix:
  include:
  - python: 3.5
    dist: trusty
    sudo: false
  - python: 3.6
    dist: trusty
    sudo: false
  - python: 3.7
    dist: xenial
    sudo: false

branches:
  only:
  - master
  - develop

install:
  - pip install -r requirements.txt

script: pytest